import type { CurrentUser, Kitchen, MenuCategory, MenuItem, Order } from '@/types/domain';

export const currentUser: CurrentUser = {
  id: 'user-1',
  role: 'employee',
  status: 'active',
  accountStatus: 'approved',
  fullName: 'Azizbek Karimov',
  phone: '+998 90 123 45 67',
  branchId: 'branch-yunusobod',
  branchName: 'Yunusobod HQ',
  branchAddress: 'Yunusobod, Amir Temur shoh kochasi 12',
  companyId: 'company-lunch-drop',
  companyName: 'Lunch Drop',
  balance: 185000,
  branches: [{ id: 'branch-yunusobod', name: 'Yunusobod HQ', address: 'Yunusobod, Amir Temur shoh kochasi 12' }],
};

export const kitchens: Kitchen[] = [
  {
    id: 'green-bowl',
    name: 'Green Bowl',
    description: 'Balanced lunch sets, salads and warm bowls.',
    rating: 4.8,
    reviewCount: 126,
    cutoffTime: '10:30',
    deliveryWindow: '12:30 - 13:00',
    distanceKm: 1.4,
    coverUrl:
      'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1200&q=80',
    isFavorite: true,
    tags: ['healthy', 'salad', 'fast'],
  },
  {
    id: 'osh-markaz',
    name: 'Osh Markaz',
    description: 'Classic Uzbek lunch with reliable office delivery.',
    rating: 4.7,
    reviewCount: 214,
    cutoffTime: '11:00',
    deliveryWindow: '13:00 - 13:30',
    distanceKm: 2.2,
    coverUrl:
      'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=1200&q=80',
    isFavorite: false,
    tags: ['uzbek', 'hot meals'],
  },
  {
    id: 'daily-bento',
    name: 'Daily Bento',
    description: 'Compact lunch boxes for teams and recurring orders.',
    rating: 4.6,
    reviewCount: 89,
    cutoffTime: '10:45',
    deliveryWindow: '12:00 - 12:30',
    distanceKm: 0.9,
    coverUrl:
      'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80',
    isFavorite: true,
    tags: ['bento', 'team lunch'],
  },
];

export const menuCategories: MenuCategory[] = [
  { id: 'sets', title: 'Lunch sets' },
  { id: 'mains', title: 'Main meals' },
  { id: 'drinks', title: 'Drinks' },
];

export const menuItems: MenuItem[] = [
  {
    id: 'protein-bowl',
    kitchenId: 'green-bowl',
    kitchenName: 'Green Bowl',
    kitchenDeliveryWindow: '12:30',
    categoryId: 'sets',
    categoryTitle: 'Lunch sets',
    name: 'Protein bowl',
    description: 'Chicken, rice, greens, avocado sauce.',
    price: 48000,
    calories: 620,
    isPopular: true,
    isAvailable: true,
    availableDays: [1, 2, 3, 4, 5],
  },
  {
    id: 'caesar-wrap',
    kitchenId: 'green-bowl',
    kitchenName: 'Green Bowl',
    kitchenDeliveryWindow: '12:30',
    categoryId: 'mains',
    categoryTitle: 'Main meals',
    name: 'Caesar wrap',
    description: 'Grilled chicken wrap with light Caesar dressing.',
    price: 39000,
    calories: 510,
    isAvailable: true,
    availableDays: [1, 2, 3, 4, 5],
  },
  {
    id: 'classic-osh',
    kitchenId: 'osh-markaz',
    kitchenName: 'Osh Markaz',
    kitchenDeliveryWindow: '13:00',
    categoryId: 'mains',
    categoryTitle: 'Main meals',
    name: 'Classic osh',
    description: 'Beef, carrots, rice and salad on the side.',
    price: 42000,
    calories: 760,
    isPopular: true,
    isAvailable: true,
    availableDays: [1, 2, 3, 4, 5],
  },
  {
    id: 'chicken-bento',
    kitchenId: 'daily-bento',
    kitchenName: 'Daily Bento',
    kitchenDeliveryWindow: '12:45',
    categoryId: 'sets',
    categoryTitle: 'Lunch sets',
    name: 'Chicken bento',
    description: 'Chicken teriyaki, rice, pickles and greens.',
    price: 52000,
    calories: 690,
    isPopular: true,
    isAvailable: true,
    availableDays: [1, 2, 3, 4, 5],
  },
  {
    id: 'lemon-tea',
    kitchenId: 'green-bowl',
    kitchenName: 'Green Bowl',
    kitchenDeliveryWindow: '12:30',
    categoryId: 'drinks',
    categoryTitle: 'Drinks',
    name: 'Lemon tea',
    description: 'Fresh brewed cold tea.',
    price: 12000,
    isAvailable: true,
    availableDays: [1, 2, 3, 4, 5],
  },
];

export const orders: Order[] = [
  {
    id: 'ord-2048',
    kitchenId: 'kitchen-1',
    kitchenName: 'Green Bowl',
    branchId: 'branch-yunusobod',
    branchName: 'Yunusobod HQ',
    status: 'on_the_way',
    statusLabel: "Yo'lda",
    items: [
      { id: 'protein-bowl', name: 'Protein bowl', quantity: 1, price: 48000 },
      { id: 'lemon-tea', name: 'Lemon tea', quantity: 1, price: 12000 },
    ],
    total: 60000,
    targetDate: '2026-06-06',
    createdAt: 'Bugun, 09:42',
    deliveryWindow: '12:30 - 13:00',
    paymentMethod: 'corporate_balance',
    paymentStatus: 'paid',
  },
  {
    id: 'ord-1982',
    kitchenId: 'kitchen-2',
    kitchenName: 'Osh Markaz',
    branchId: 'branch-yunusobod',
    branchName: 'Yunusobod HQ',
    status: 'delivered',
    statusLabel: 'Yetkazildi',
    items: [{ id: 'classic-osh', name: 'Classic osh', quantity: 1, price: 42000 }],
    total: 42000,
    targetDate: '2026-06-05',
    createdAt: 'Kecha, 10:18',
    deliveryWindow: '13:00 - 13:30',
    paymentMethod: 'corporate_balance',
    paymentStatus: 'paid',
  },
];
